# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c953d124d110c804091b9ceae61b44f73ab4463b346291f55370c9ef95e2908d02c72dbfd09808e5e666d0e3e2647d588b525cc702d361b7812ebce07bb784d3

test:
  secret_key_base: 03cab4915997284a4c0e2d1bcfd1c7cc5e1f4bd7f9089d8bace666bf8f40aeeaea97ebc4866582fde8ce0ec8e64e2e013221d98208af11953909d4aa9db4efc5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
